extends Node

const CARDS = {
	"Blue" : {
		"type": "character",
		"action_type": null,
		"card_number": 1,
		"card_type": "Color Crew",
		"rarity": "common",
	},
	"Red" : {
		"type": "character",
		"action_type": null,
		"card_number": 2,
		"card_type": "Color Crew",
		"rarity": "common",
	},
	"Green" : {
		"type": "character",
		"action_type": null,
		"card_number": 3,
		"card_type": "Color Crew",
		"rarity": "common",
	},
	"Black" : {
		"type": "character",
		"action_type": null,
		"card_number": 4,
		"card_type": "Color Crew",
		"rarity": "rare",
	},
	"BottleOPoison" : {
		"type": "action",
		"action_type": "single_card_select",
		"card_number": 5,
		"card_type": "Flipping Magic",
		"rarity": "common",
	},
	"BuffUp" : {
		"type": "action",
		"action_type": "reaction",
		"card_number": 6,
		"card_type": "Power Ups",
		"rarity": "rare",
	},
	"Drill" : {
		"type": "action",
		"action_type": "column_select",
		"card_number": 7,
		"card_type": "Tools",
		"rarity": "rare",
	},
	"DoctorDucttape" : {
		"type": "action",
		"action_type": "board_select",
		"card_number": 8,
		"card_type": null,
		"rarity": "common",
	},
	"ExtraLimbs" : {
		"type": "action",
		"action_type": "board_select",
		"card_number": 9,
		"card_type": "Monster Match",
		"rarity": "common",
	},
	"FireSpirit" : {
		"type": "action",
		"action_type": "single_card_select",
		"card_number": 10,
		"card_type": "Spirits",
		"rarity": "common",
	},
	"IceSpirit" : {
		"type": "action",
		"action_type": "single_card_select",
		"card_number": 11,
		"card_type": "Spirits",
		"rarity": "common",
	},
	"LeDuck" : {
		"type": "character",
		"action_type": null,
		"card_number": 12,
		"card_type": "Le Farm",
		"rarity": "common",
	},
	"Mirror" : {
		"type": "action",
		"action_type": "match_select",
		"card_number": 13,
		"card_type": "Flipping Magic",
		"rarity": "common",
	},
	"Orange" : {
		"type": "character",
		"action_type": null,
		"card_number": 14,
		"card_type": "Color Crew",
		"rarity": "common",
	},
	"Purple" : {
		"type": "character",
		"action_type": null,
		"card_number": 15,
		"card_type": "Color Crew",
		"rarity": "common",
	},
	"Skeleton" : {
		"type": "character",
		"action_type": null,
		"card_number": 16,
		"card_type": "Monster Match",
		"rarity": "common",
	},
	"White" : {
		"type": "character",
		"action_type": null,
		"card_number": 17,
		"card_type": "Color Crew",
		"rarity": "rare",
	},
	"Yellow" : {
		"type": "character",
		"action_type": null,
		"card_number": 18,
		"card_type": "Color Crew",
		"rarity": "common",
	},
	"JackOBoom" : {
		"type": "action",
		"action_type": "single_card_select",
		"card_number": 19,
		"card_type": "Monster Match",
		"rarity": "rare",
	},
	"Alacazam" : {
		"type": "action",
		"action_type": "single_card_select",
		"card_number": 20,
		"card_type": "Flipping Magic",
		"rarity": "rare",
	},
	"CardFishing": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 21,
		"card_type": null,
		"rarity": "common",
	},
	"HotHands": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 22,
		"card_type": null,
		"rarity": "rare",
	},
	"JackHammer": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 23,
		"card_type": "Tools",
		"rarity": "epic",
	},
	"BushShaman": {
		"type": "character",
		"action_type": null,
		"card_number": 24,
		"card_type": "Shaman Island",
		"rarity": "common",
	},
	"FrostShaman": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 25,
		"card_type": "Shaman Island",
		"rarity": "rare",
	},
	"VolcanoShaman": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 26,
		"card_type": "Shaman Island",
		"rarity": "rare",
	},
	"ShamansCoconut": {
		"type": "character",
		"action_type": null,
		"card_number": 27,
		"card_type": "Shaman Island",
		"rarity": "common",
	},
	"ShrinkShaman": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 28,
		"card_type": "Shaman Island",
		"rarity": "rare",
	},
	"Sha-Shaman-Man": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 29,
		"card_type": "Shaman Island",
		"rarity": "epic",
	},
	"MagmaSlime": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 30,
		"card_type": "Twisted Fantasy",
		"rarity": "rare",
	},
	"EnlightenUp": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 31,
		"card_type": "Power Ups",
		"rarity": "common",
	},
	"FatUp": {
		"type": "action",
		"action_type": "match_select",
		"card_number": 32,
		"card_type": "Power Ups",
		"rarity": "common",
	},
	"ColorWheel": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 33,
		"card_type": "Color Crew",
		"rarity": "epic",
	},
	"BottleOSlime": {
		"type": "action",
		"action_type": "single_card_select",
		"card_number": 34,
		"card_type": "Flipping Magic",
		"rarity": "rare",
	},
	"BottleOLightning": {
		"type": "action",
		"action_type": "single_card_select",
		"card_number": 35,
		"card_type": "Flipping Magic",
		"rarity": "rare",
	},
	"Ghost": {
		"type": "character",
		"action_type": null,
		"card_number": 36,
		"card_type": "Monster Match",
		"rarity": "common",
	},
	"Demon": {
		"type": "character",
		"action_type": null,
		"card_number": 37,
		"card_type": "Monster Match",
		"rarity": "rare",
	},
	"SambaSnake": {
		"type": "character",
		"action_type": null,
		"card_number": 38,
		"card_type": "Danssse Floor",
		"rarity": "rare",
	},
	"SambaSauce": {
		"type": "character",
		"action_type": null,
		"card_number": 39,
		"card_type": "Danssse Floor",
		"rarity": "common",
	},
	"Jump": {
		"type": "action",
		"action_type": "single_card_select",
		"card_number": 40,
		"card_type": "Danssse Floor",
		"rarity": "common",
	},
	"Slide": {
		"type": "action",
		"action_type": "reaction",
		"card_number": 41,
		"card_type": "Danssse Floor",
		"rarity": "rare",
	},
	"Slither": {
		"type": "action",
		"action_type": "reaction",
		"card_number": 42,
		"card_type": "Danssse Floor",
		"rarity": "epic",
	},
	"RogueBandit": {
		"type": "action",
		"action_type": "reaction",
		"card_number": 43,
		"card_type": "Rogue Forest",
		"rarity": "rare",
	},
	"Maidmer": {
		"type": "character",
		"action_type": null,
		"card_number": 44,
		"card_type": "Twisted Fantasy",
		"rarity": "rare",
	},
	"RogueBerserker": {
		"type": "action",
		"action_type": "reaction",
		"card_number": 45,
		"card_type": "Rogue Forest",
		"rarity": "epic",
	},
	"NutsandBolts": {
		"type": "character",
		"action_type": null,
		"card_number": 46,
		"card_type": "Tools",
		"rarity": "common",
	},
	"BottleOClean": {
		"type": "action",
		"action_type": "board_select",
		"card_number": 47,
		"card_type": "Flipping Magic",
		"rarity": "rare",
	},
	"MetalPlatedMatch": {
		"type": "action",
		"action_type": "match_select",
		"card_number": 48,
		"card_type": "Tools",
		"rarity": "rare",
	},
	"LePig": {
		"type": "character",
		"action_type": null,
		"card_number": 49,
		"card_type": "Le Farm",
		"rarity": "common",
	},
	"LeGoat": {
		"type": "character",
		"action_type": null,
		"card_number": 50,
		"card_type": "Le Farm",
		"rarity": "common",
	},
	"RogueWarlock": {
		"type": "action",
		"action_type": "reaction",
		"card_number": 51,
		"card_type": "Rogue Forest",
		"rarity": "epic",
	},
	"SchoolOfMaidMer": {
		"type": "action",
		"action_type": "row_select",
		"card_number": 52,
		"card_type": "Twisted Fantasy",
		"rarity": "epic",
	}
}
